name: security-pr
on:
  pull_request:

permissions:
  actions: read
  security-events: write
  contents: read

jobs:
  # Job #1 : Analyse des dépendances différentielle
  dependencies-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code (after PR)
        uses: actions/checkout@v4

      - name: Run OSV Scanner after PR
        uses: google/osv-scanner-action/osv-scanner-action@7222d1c7ee4f96d71d883e0d3c603f1e1705eca9 # v2.3.5
        with:
          scan-args: |-
            --format sarif
            --output AfterPR.sarif
            ./
        continue-on-error: true

      - name: Checkout baseline commit (before PR)
        run: |
          git checkout ${{ github.event.pull_request.base.sha }}

      - name: Run OSV Scanner before PR
        uses: google/osv-scanner-action/osv-scanner-action@7222d1c7ee4f96d71d883e0d3c603f1e1705eca9 # v2.3.5
        with:
          scan-args: |-
            --format sarif
            --output BeforePR.sarif
            ./
        continue-on-error: true

      - name: Compare analysis (differential report)
        uses: google/osv-scanner-action/osv-reporter-action@7222d1c7ee4f96d71d883e0d3c603f1e1705eca9 # v2.3.5
        with:
          scan-args: |-
            --new BeforePR.sarif
            --old AfterPR.sarif
            --output DifferentialDependencies.sarif
            --format sarif
        continue-on-error: true

      - name: Save differential report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: DifferentialDependencies
          path: DifferentialDependencies.sarif

  # Job #2 : Analyse du code source différentielle
  source-code-analysis:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep@sha256:98483a9a30707d88f8826b9b1995e53a83a01016e8cd325119b0d8054a481269
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Run Semgrep differential analysis
        run: |
          semgrep \
            --config .semgrep \
            --sarif \
            --output SourceCodeDifferential.sarif \
            --baseline-commit ${{ github.event.pull_request.base.sha }} \
            ./
        continue-on-error: true

      - name: Save differential report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SourceCodeDifferential
          path: SourceCodeDifferential.sarif
