name: security-pr

on:
  pull_request:

permissions:
  actions: read
  security-events: write
  contents: read

jobs:

  dependencies-analysis:
    name: dependencies-analysis
    runs-on: ubuntu-latest

    steps:

      - name: Checkout code (after PR)
        uses: actions/checkout@v4

      - name: Run OSV Scanner after PR
        uses: google/osv-scanner-action/osv-scanner-action@v2.3.5
        with:
          scan-args: |-
            --format sarif
            --output AfterPR.sarif
            ./
        continue-on-error: true


      - name: Checkout baseline commit (before PR)
        run: |
          git checkout ${{ github.event.pull_request.base.sha }}


      - name: Run OSV Scanner before PR
        uses: google/osv-scanner-action/osv-scanner-action@v2.3.5
        with:
          scan-args: |-
            --format sarif
            --output BeforePR.sarif
            ./
        continue-on-error: true


      - name: Compare analysis (differential report)
        uses: google/osv-scanner-action/osv-reporter-action@v2.3.5
        with:
          scan-args: |-
            --new AfterPR.sarif
            --old BeforePR.sarif
            --output DifferentialDependencies.sarif
            --format sarif
        continue-on-error: true


      - name: Save differential report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: DifferentialDependencies
          path: DifferentialDependencies.sarif



  source-code-analysis:
    name: source-code-analysis
    runs-on: ubuntu-latest

    container:
      image: returntocorp/semgrep:latest

    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0


      - name: Run Semgrep differential analysis
        run: |
          semgrep \
            --config .semgrep \
            --sarif \
            --output SourceCodeDifferential.sarif \
            --baseline-commit ${{ github.event.pull_request.base.sha }} \
            ./
        continue-on-error: true


      - name: Save differential report as artifact
        uses: actions/upload-artifact@v4
        with:
          name: SourceCodeDifferential
          path: SourceCodeDifferential.sarif
